NineNinecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :update, :edit]
  
end

NineNinecats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NineNinecats/app/models/cat.rb
require 'action_view'

# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    COLORS = ['Blue', 'Brown', 'Red', 'Purple', 'Yellow', 'Black', 'White', 'Green', 'Orange']

    validates :birth_date, presence: true
    validates :color, inclusion: COLORS

    def self.colors
        return COLORS
    end

    def age
        distance_of_time_in_words_to_now(birth_date)

        # today = Date.today
        # d = Date.new(today.year, dob.month, dob.day)
        # age = d.year - dob.year - (d > today ? 1 : 0)

        # now = Time.now.utc.to_date
        # now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
end

NineNinecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

NineNinecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        cat = Cat.find(params[:id])
        if cat.update(cat_params)
            redirect_to cat_url(cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

NineNinecats/app/helpers/application_helper.rb
module ApplicationHelper
end

NineNinecats/app/views/cats/_form.html.erb
<% if edit %>
    <% action = cat_url(cat) %>
    <% button_text = "Edit the Cat" %>
<% else %>
    <% action = cats_url %>
    <% button_text = "Create a Cat" %>
<% end %>
<form action="<%= action %>" method="post">
    <% if edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <label>Name
        <input type="text" name="cat[name]" id="name" value="<%= cat.name %>">
    </label>
    <label>Birth Date
        <input type="date" name="cat[birth_date]" id="birth_date" value="<%= cat.birth_date %>">
    </label>
    <label>Color
        <select name="cat[color]" id="color">
            <% Cat.colors.each do |color| %>
                <option value="<%= color %>">
                    <%= color %>
                </option>
            <% end %>
        </select>
    </label>
    <label>Sex
        <input type="radio" name="cat[sex]" id="sex_m" value="M">  
        <label for="sex_m">M</label>

        <input type="radio" name="cat[sex]" id="sex_f" value="F">  
        <label for="sex_f">F</label>

    </label>
    <label>Description
        <textarea name="cat[description]" id="description" value="<%= cat.description %>">
        </textarea>
    </label>

    <input type="submit" value="<%= button_text %>"> 
</form>

NineNinecats/app/views/cats/edit.html.erb
<h1>Update a Cat</h1>

<%= render "form", edit: true, cat: @cat %>

NineNinecats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<a href="<%= new_cat_url %>">Create a new Cat</a>

<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.name %></li>
        <a href="<%= cat_url(cat) %>">Show the Cat</a>
    <% end %>
</ul>

NineNinecats/app/views/cats/new.html.erb
<h1>Create a Cat</h1>

<%= render "form", edit: false, cat: @cat %>

NineNinecats/app/views/cats/show.html.erb
<a href="<%= edit_cat_url %>">Create a new Cat</a>

<table>
    <thead>
        <tr>
            <th colspan ="2"><h1><%= @cat.name %></h1></th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>Birth Date</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
            </tr>
        <tr>
            <td>Name</td>
            <td><%= @cat.name %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Age</td>
            <td><%= @cat.age %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>

</table>

<a href="<%= cats_url %>">Show all Cats</a>

NineNinecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NineNinecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>